### ISSUE TITLE
Roadmap, WIP

### ISSUE THREAD

**Issue by CinquinAndy** [CinquinAndy/export-repository-to-prompt-for-llm#35]
- [ ] Sur le projet d'export prompt : split en plusieurs fichiers de 2k + un fichier global recap 
- [ ] Sur le projet d'export prompt : Mettre ça dans un dossier externe 
- [ ] Sur le projet d'export prompt : faire un fichier json de conf général 
- [ ] Sur le projet d'export prompt : faire un readme clean recap 
- [ ] Sur le projet d'export prompt : clean le npm repo (ça marche pas pour le moment)
